spring.application.name=Zavrsni
server.port=8082
spring.datasource.url=jdbc:sqlserver://localhost:50202;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=JavaAdv;
spring.datasource.username=hardware
spring.datasource.password=hardware
